### ISSUE TITLE
Document negative keys in vocabularies

### ISSUE THREAD

**Issue by attilaolah** [bluedynamics/yafowil.yaml#1]
A vocabulary like this:

``` yaml
widgets:
- foo:
    factory: "*number:select"
    value: -1
    props:
        vocabulary:
          -1: "Minus one"
          1: "Plus one"
```

does not work, as it is invalid YAML. To make stuff like this work, inlined JSON can be used to represent the vocabulary as a list of key-value pairs, instead of using a direct mapping, like so:

``` yaml
widgets:
- foo:
    factory: "*number:select"
    value: -1
    props:
        vocabulary:
          - [-1, "Minus one"]
          - [1, "Plus one"]
```

If this is desired behavior, maybe a word or two should be added about this to the docs.
